"""Public schema generation tests for contract models."""

from __future__ import annotations

from agent_driver.contracts import (
    AgentProfile,
    AgentRunInput,
    AgentRunOutput,
    ApprovalPayload,
    CapabilityPackResolution,
    CheckpointRef,
    EvidenceArtifactIndex,
    EvidenceArtifactRef,
    ExecutorSerializationPolicy,
    HarnessAdapterCapability,
    HarnessAdapterCompatibilityReport,
    HarnessAdapterControl,
    HarnessAdapterEvent,
    HarnessAdapterManifest,
    HarnessAdapterRun,
    HarnessAdapterSession,
    HarnessApprovalRequest,
    HarnessArtifactRef,
    HarnessCapabilityPack,
    HarnessReleaseGate,
    HarnessScenarioSpec,
    HarnessSupportBundleRef,
    InterruptRequest,
    MemoryProjection,
    PromptRenderResult,
    PromptTemplate,
    ResumeCommand,
    RuntimeEvent,
    SubagentGroup,
    SubagentRun,
    ToolManifest,
    ToolResultEnvelope,
    ToolTrace,
)

PUBLIC_CONTRACT_FIELD_SNAPSHOTS: dict[str, tuple[str, ...]] = {
    "AgentRunInput": (
        "input",
        "messages",
        "thread_id",
        "run_id",
        "resume",
        "agent_id",
        "graph_preset",
        "agent_profile",
        "model_role",
        "stream",
        "prompt_template_id",
        "prompt_template_version",
        "serialization_policy",
        "tool_policy",
        "node_contract",
        "goal_contract",
        "deadline_seconds",
        "max_steps",
        "max_tool_calls",
        "cost_budget_usd",
        "temperature",
        "max_tokens",
        "user_id",
        "tenant_id",
        "workspace_id",
        "structured_output",
        "request_only_context",
        "app_metadata",
        "response_format",
        "tool_choice",
    ),
    "AgentRunOutput": (
        "run_id",
        "attempt_id",
        "thread_id",
        "status",
        "answer",
        "messages",
        "events",
        "tool_trace",
        "subagent_runs",
        "subagent_groups",
        "artifacts",
        "memory_projection",
        "prompt_render",
        "usage",
        "warnings",
        "trace",
        "checkpoint",
        "interrupt",
        "memory_audit",
        "terminal_reason",
        "context",
        "metadata",
    ),
    "RuntimeEvent": (
        "event_id",
        "type",
        "run_id",
        "attempt_id",
        "seq",
        "created_at",
        "checkpoint_id",
        "node_id",
        "payload",
        "trace_id",
        "severity",
        "redaction",
    ),
    "ToolManifest": (
        "name",
        "description",
        "risk",
        "side_effect",
        "approval_mode",
        "timeout_seconds",
        "output_char_budget",
        "idempotent",
        "concurrency_safe",
        "interrupt_behavior",
        "should_defer",
        "always_load",
        "aliases",
        "max_result_size_chars",
        "success_field",
        "args_schema",
        "output_type",
        "output_schema",
        "remediation_hints",
        "supported_profiles",
        "metadata",
    ),
    "ToolTrace": (
        "step",
        "tool_name",
        "tool_call_id",
        "status",
        "args_summary",
        "result_summary",
        "artifact_refs",
        "risk",
        "side_effect",
        "approval_mode",
        "duration_ms",
        "error_code",
        "truncated",
        "metadata",
    ),
    "ToolResultEnvelope": (
        "call",
        "decision",
        "guardrail_decision",
        "summary",
        "structured_output",
        "artifacts",
        "truncated",
        "error",
        "interrupt",
        "metadata",
    ),
    "InterruptRequest": (
        "interrupt_id",
        "run_id",
        "attempt_id",
        "checkpoint_id",
        "reason",
        "title",
        "description",
        "risk",
        "proposed_action",
        "allowed_actions",
        "editable_fields",
        "proposed_prompts",
        "expires_at",
        "metadata",
    ),
    "ResumeCommand": (
        "interrupt_id",
        "action",
        "message",
        "edited_tool_args",
        "state_patch",
        "approved_by",
        "created_at",
        "idempotency_key",
        "expected_checkpoint_id",
        "approved_prompts",
        "metadata",
    ),
    "ApprovalPayload": (
        "interrupt_id",
        "reason",
        "title",
        "description",
        "risk",
        "tool_name",
        "tool_call_id",
        "args_preview",
        "allowed_actions",
        "editable_fields",
        "metadata",
    ),
    "HarnessReleaseGate": (
        "gate_id",
        "gate_class",
        "required",
        "command",
        "evidence_paths",
        "skip_condition",
        "max_cost_usd",
        "max_flake_budget",
        "redacted_metadata",
    ),
    "HarnessCapabilityPack": (
        "pack_id",
        "version",
        "target_product_family",
        "status",
        "provider_route_requirements",
        "policy_profile_defaults",
        "supervision_expectations",
        "required_evidence",
        "required_skills",
        "context_requirements",
        "side_effect_classes",
        "release_gates",
        "rollout_mode",
        "compatibility",
        "owners",
        "ownership_notes",
        "review_checklist",
        "notes",
    ),
    "HarnessScenarioSpec": (
        "scenario_id",
        "status",
        "product_adapter_id",
        "prompt_seed",
        "task_seed",
        "required_tools",
        "required_evidence",
        "expected_policy_verdicts",
        "expected_provenance_verdicts",
        "expected_supervisor_verdicts",
        "deterministic_gate_ids",
        "optional_live_gate_ids",
        "artifact_paths",
        "skip_conditions",
        "redacted_metadata",
    ),
    "HarnessAdapterManifest": (
        "adapter_id",
        "product_name",
        "product_family",
        "expected_ports",
        "env_var_names",
        "start_commands",
        "deterministic_commands",
        "optional_live_commands",
        "trace_endpoints",
        "support_bundle_endpoints",
        "benchmark_commands",
        "playwright_specs",
        "artifact_output_paths",
        "known_non_goals",
        "redacted_metadata",
    ),
    "HarnessArtifactRef": (
        "artifact_id",
        "artifact_type",
        "path",
        "uri",
        "sha256",
        "gate_id",
        "scenario_id",
        "redacted_metadata",
    ),
    "HarnessSupportBundleRef": (
        "bundle_id",
        "bundle_type",
        "path",
        "uri",
        "sha256",
        "gate_id",
        "redacted_metadata",
    ),
    "HarnessApprovalRequest": (
        "request_id",
        "run_id",
        "attempt_id",
        "tool_name",
        "tool_call_id",
        "side_effect_class",
        "arguments_summary",
        "policy_verdict",
        "expires_at",
        "response_options",
        "redacted_details",
    ),
    "HarnessAdapterEvent": (
        "event_id",
        "session_id",
        "run_id",
        "attempt_id",
        "cursor",
        "seq",
        "kind",
        "category",
        "state",
        "source",
        "display",
        "redacted_metadata",
        "artifact_refs",
        "support_bundle_refs",
        "approval_request",
        "created_at",
    ),
    "HarnessAdapterSession": (
        "session_id",
        "thread_id",
        "adapter_id",
        "cwd",
        "provider_route_summary",
        "mode",
        "lifecycle_state",
        "durability_level",
        "created_at",
        "updated_at",
        "redacted_metadata",
        "support_bundle_refs",
    ),
    "HarnessAdapterRun": (
        "run_id",
        "attempt_id",
        "session_id",
        "current_cursor",
        "lifecycle_state",
        "durability_level",
        "supervisor_summary",
        "capability_pack_ids",
        "scenario_ids",
        "artifact_refs",
        "support_bundle_refs",
        "compatibility_flags",
        "redacted_metadata",
    ),
    "HarnessAdapterControl": (
        "control_id",
        "control_kind",
        "session_id",
        "run_id",
        "cursor",
        "payload",
        "requested_by",
        "created_at",
        "redacted_metadata",
    ),
    "HarnessAdapterCapability": (
        "adapter_id",
        "product_family",
        "protocol",
        "durability_level",
        "features",
        "scenario_ids",
        "redacted_metadata",
    ),
    "HarnessAdapterCompatibilityReport": (
        "report_id",
        "adapter_id",
        "product_family",
        "protocol",
        "generated_at",
        "no_live",
        "capability",
        "feature_statuses",
        "session",
        "run",
        "event_count",
        "artifact_refs",
        "support_bundle_refs",
        "scenario_ids",
        "validation_gate_statuses",
        "skipped_reasons",
        "redaction",
        "redacted_metadata",
    ),
    "EvidenceArtifactRef": (
        "artifact_id",
        "artifact_type",
        "path",
        "uri",
        "sha256",
        "gate_id",
        "redacted_metadata",
    ),
    "EvidenceArtifactIndex": (
        "index_id",
        "pack_id",
        "pack_version",
        "scenario_ids",
        "gates",
        "artifacts",
        "skipped_gate_ids",
        "redaction",
    ),
    "CapabilityPackResolution": (
        "pack_id",
        "pack_version",
        "adapter_id",
        "scenario_ids",
        "selected_gate_ids",
        "required_evidence",
        "required_skills",
        "context_requirements",
        "provider_route_requirements",
        "policy_profile_defaults",
        "supervision_expectations",
        "gate_statuses",
        "skipped_gate_ids",
        "skipped_gate_reasons",
        "deterministic_commands",
        "optional_live_commands",
        "evidence_index",
        "rollout_mode",
        "compatibility",
        "redacted_metadata",
    ),
}


def test_public_contract_schema_generation() -> None:
    """Ensure JSON schemas are generated for key public contracts."""
    schema = {
        "AgentRunInput": AgentRunInput.model_json_schema(),
        "AgentRunOutput": AgentRunOutput.model_json_schema(),
        "RuntimeEvent": RuntimeEvent.model_json_schema(),
        "CheckpointRef": CheckpointRef.model_json_schema(),
        "ResumeCommand": ResumeCommand.model_json_schema(),
        "InterruptRequest": InterruptRequest.model_json_schema(),
        "ToolTrace": ToolTrace.model_json_schema(),
        "SubagentRun": SubagentRun.model_json_schema(),
        "SubagentGroup": SubagentGroup.model_json_schema(),
        "PromptTemplate": PromptTemplate.model_json_schema(),
        "PromptRenderResult": PromptRenderResult.model_json_schema(),
        "MemoryProjection": MemoryProjection.model_json_schema(),
        "ExecutorSerializationPolicy": ExecutorSerializationPolicy.model_json_schema(),
        "ApprovalPayload": ApprovalPayload.model_json_schema(),
        "HarnessReleaseGate": HarnessReleaseGate.model_json_schema(),
        "HarnessCapabilityPack": HarnessCapabilityPack.model_json_schema(),
        "HarnessScenarioSpec": HarnessScenarioSpec.model_json_schema(),
        "HarnessAdapterManifest": HarnessAdapterManifest.model_json_schema(),
        "HarnessArtifactRef": HarnessArtifactRef.model_json_schema(),
        "HarnessSupportBundleRef": HarnessSupportBundleRef.model_json_schema(),
        "HarnessApprovalRequest": HarnessApprovalRequest.model_json_schema(),
        "HarnessAdapterEvent": HarnessAdapterEvent.model_json_schema(),
        "HarnessAdapterSession": HarnessAdapterSession.model_json_schema(),
        "HarnessAdapterRun": HarnessAdapterRun.model_json_schema(),
        "HarnessAdapterControl": HarnessAdapterControl.model_json_schema(),
        "HarnessAdapterCapability": HarnessAdapterCapability.model_json_schema(),
        "HarnessAdapterCompatibilityReport": (
            HarnessAdapterCompatibilityReport.model_json_schema()
        ),
        "EvidenceArtifactRef": EvidenceArtifactRef.model_json_schema(),
        "EvidenceArtifactIndex": EvidenceArtifactIndex.model_json_schema(),
        "CapabilityPackResolution": CapabilityPackResolution.model_json_schema(),
    }

    assert "properties" in schema["AgentRunInput"]
    assert "properties" in schema["AgentRunOutput"]
    assert "status" in schema["AgentRunOutput"]["properties"]
    assert "type" in schema["RuntimeEvent"]["properties"]
    assert "checkpoint_id" in schema["CheckpointRef"]["properties"]
    assert "action" in schema["ResumeCommand"]["properties"]
    assert "allowed_actions" in schema["InterruptRequest"]["properties"]
    assert "tool_name" in schema["ToolTrace"]["properties"]
    assert "terminal_state" in schema["SubagentRun"]["properties"]
    assert "join_policy" in schema["SubagentGroup"]["properties"]
    assert "profile" in schema["PromptTemplate"]["properties"]
    assert "rendered_hash" in schema["PromptRenderResult"]["properties"]
    assert "steps" in schema["MemoryProjection"]["properties"]
    assert "mode" in schema["ExecutorSerializationPolicy"]["properties"]
    assert "allowed_actions" in schema["ApprovalPayload"]["properties"]
    assert "pack_id" in schema["HarnessCapabilityPack"]["properties"]
    assert "scenario_id" in schema["HarnessScenarioSpec"]["properties"]
    assert "adapter_id" in schema["HarnessAdapterManifest"]["properties"]
    assert "cursor" in schema["HarnessAdapterEvent"]["properties"]
    assert (
        "feature_statuses" in schema["HarnessAdapterCompatibilityReport"]["properties"]
    )
    assert "artifacts" in schema["EvidenceArtifactIndex"]["properties"]
    assert "gate_statuses" in schema["CapabilityPackResolution"]["properties"]
    assert AgentProfile.REACT_TEXT.value in str(schema["PromptTemplate"])


def test_public_contract_field_snapshots() -> None:
    """Pin top-level public contract field names before SDK stabilization."""
    models = {
        "AgentRunInput": AgentRunInput,
        "AgentRunOutput": AgentRunOutput,
        "RuntimeEvent": RuntimeEvent,
        "ToolManifest": ToolManifest,
        "ToolTrace": ToolTrace,
        "ToolResultEnvelope": ToolResultEnvelope,
        "InterruptRequest": InterruptRequest,
        "ResumeCommand": ResumeCommand,
        "ApprovalPayload": ApprovalPayload,
        "HarnessReleaseGate": HarnessReleaseGate,
        "HarnessCapabilityPack": HarnessCapabilityPack,
        "HarnessScenarioSpec": HarnessScenarioSpec,
        "HarnessAdapterManifest": HarnessAdapterManifest,
        "HarnessArtifactRef": HarnessArtifactRef,
        "HarnessSupportBundleRef": HarnessSupportBundleRef,
        "HarnessApprovalRequest": HarnessApprovalRequest,
        "HarnessAdapterEvent": HarnessAdapterEvent,
        "HarnessAdapterSession": HarnessAdapterSession,
        "HarnessAdapterRun": HarnessAdapterRun,
        "HarnessAdapterControl": HarnessAdapterControl,
        "HarnessAdapterCapability": HarnessAdapterCapability,
        "HarnessAdapterCompatibilityReport": HarnessAdapterCompatibilityReport,
        "EvidenceArtifactRef": EvidenceArtifactRef,
        "EvidenceArtifactIndex": EvidenceArtifactIndex,
        "CapabilityPackResolution": CapabilityPackResolution,
    }

    for name, model in models.items():
        assert tuple(model.model_fields) == PUBLIC_CONTRACT_FIELD_SNAPSHOTS[name]
