"""Shared expected built-in tool names for registry coverage tests."""

from __future__ import annotations

EXPECTED_BUILTIN_TOOL_NAMES = {
    "read_file",
    "task_create",
    "workflow_tool",
    "file_edit",
    "mcp_tool",
    "team_create_tool",
    "web_search",
    "lsp_tool",
    "glob_search",
    "cron_create_tool",
    "team_get_tool",
    "task_get",
    "powershell_tool",
    "send_user_file_tool",
    "file_write",
    "task_list",
    "bash",
    "tool_search",
    "team_list_tool",
    "subscribe_pr_tool",
    "monitor_tool",
    "task_stop_tool",
    "remote_trigger_tool",
    "mcp_auth",
    "exit_plan_mode_v2",
    "skill_tool",
    "skill_view",
    "send_message_tool",
    "notebook_edit",
    "enter_plan_mode",
    "brief_tool",
    "task_update",
    "grep_search",
    "mcp_list_resources",
    "push_notification_tool",
    "agent_tool",
    "team_delete_tool",
    "mcp_read_resource",
    "cron_list_tool",
    "sleep_tool",
    "list_peers_tool",
    "enter_worktree_tool",
    "exit_worktree_tool",
    "cron_delete_tool",
    "todo_write",
    "ask_user_question",
    "task_output",
    "web_fetch",
}

__all__ = ["EXPECTED_BUILTIN_TOOL_NAMES"]
