"""LLM gateway package exports."""

from agent_driver.llm.aux import (
    AuxCachePrefix,
    aux_completion,
    aux_fork_event_payload,
    merge_aux_usage,
)
from agent_driver.llm.contracts import (
    LlmFinishReason,
    LlmProviderKind,
    LlmRequest,
    LlmResponse,
    LlmStreamEvent,
    ProviderStatus,
    RouterStrategy,
)
from agent_driver.llm.error_classifier import (
    ClassifiedError,
    ProviderErrorReason,
    RecoveryAction,
    classify,
)
from agent_driver.llm.provider_catalog import (
    ProviderPluginRegistry,
    bridge_provider_descriptor,
    build_provider_compatibility_report,
    build_provider_routing_plan,
    provider_catalog_support_metadata,
    render_provider_compatibility_markdown,
    seed_provider_capability_matrix,
    seed_provider_catalogs,
    seed_provider_plugin_manifests,
    seed_provider_plugin_registry,
    seed_provider_preflight_reports,
    seed_provider_route_plugins,
    seed_provider_routing_plans,
    seed_provider_sanitizer_fixtures,
    write_provider_catalog_artifacts,
)
from agent_driver.llm.provider_descriptors import (
    ProviderDescriptor,
    ProviderResolutionError,
    ProviderSpec,
    ProviderTransport,
    get_provider_descriptor,
    list_provider_ids,
    register_provider_descriptor,
    resolve_provider,
)
from agent_driver.llm.provider_route_profiles import (
    ProviderPreflightResult,
    ProviderRequestShapePlan,
    ProviderRouteProfile,
    build_provider_request_shape_plan,
    preview_provider_preflight,
    request_shape_policy_summary,
    resolve_openai_compatible_route_profile,
)
from agent_driver.llm.providers import LlmProvider
from agent_driver.llm.providers_impl import (
    FakeProvider,
    OllamaProvider,
    OpenAICompatibleProvider,
)
from agent_driver.llm.model_router import (
    AsyncModelRouter,
    HeuristicDifficultyRouter,
    LlmDifficultyRouter,
    ModelRouter,
    PlanExecuteRouter,
    RouteContext,
    last_user_text,
)
from agent_driver.llm.router import HealthAwareRouter
from agent_driver.llm.sanitize import sanitize_request_messages, strip_surrogates
from agent_driver.llm.structured import (
    StructuredOutputError,
    structured_completion,
)
from agent_driver.llm.suggestions import (
    filter_suggestion,
    generate_suggestions,
    suppress_reason_for_usage,
)

__all__ = [
    "AuxCachePrefix",
    "aux_completion",
    "aux_fork_event_payload",
    "merge_aux_usage",
    "filter_suggestion",
    "generate_suggestions",
    "suppress_reason_for_usage",
    "sanitize_request_messages",
    "strip_surrogates",
    "ClassifiedError",
    "FakeProvider",
    "HealthAwareRouter",
    "AsyncModelRouter",
    "HeuristicDifficultyRouter",
    "LlmDifficultyRouter",
    "ModelRouter",
    "PlanExecuteRouter",
    "RouteContext",
    "last_user_text",
    "LlmFinishReason",
    "ProviderDescriptor",
    "ProviderPreflightResult",
    "ProviderPluginRegistry",
    "ProviderRequestShapePlan",
    "ProviderErrorReason",
    "ProviderResolutionError",
    "ProviderRouteProfile",
    "ProviderSpec",
    "ProviderTransport",
    "RecoveryAction",
    "classify",
    "bridge_provider_descriptor",
    "build_provider_request_shape_plan",
    "build_provider_compatibility_report",
    "build_provider_routing_plan",
    "get_provider_descriptor",
    "list_provider_ids",
    "provider_catalog_support_metadata",
    "register_provider_descriptor",
    "render_provider_compatibility_markdown",
    "preview_provider_preflight",
    "request_shape_policy_summary",
    "resolve_openai_compatible_route_profile",
    "resolve_provider",
    "seed_provider_capability_matrix",
    "seed_provider_catalogs",
    "seed_provider_plugin_manifests",
    "seed_provider_plugin_registry",
    "seed_provider_preflight_reports",
    "seed_provider_route_plugins",
    "seed_provider_routing_plans",
    "seed_provider_sanitizer_fixtures",
    "write_provider_catalog_artifacts",
    "LlmProvider",
    "LlmProviderKind",
    "LlmRequest",
    "LlmResponse",
    "LlmStreamEvent",
    "StructuredOutputError",
    "structured_completion",
    "OllamaProvider",
    "OpenAICompatibleProvider",
    "ProviderStatus",
    "RouterStrategy",
]
