"""Shared Agent Skills parsing, listing and viewing helpers."""

from agent_driver.skills.catalog import build_skills_catalog_block
from agent_driver.skills.curated import CURATED_RESEARCH_SKILL_NAMES, curated_skills_dir
from agent_driver.skills.models import SkillInvocation, SkillManifest
from agent_driver.skills.parser import (
    SKILL_FILENAME,
    clear_skill_manifest_cache,
    is_trusted_path,
    load_skill_manifest,
    parse_frontmatter,
    split_frontmatter,
)
from agent_driver.skills.registry import (
    SkillView,
    list_skill_manifests,
    skill_manifest_payload,
    view_skill,
)
from agent_driver.skills.lifecycle import (
    build_skill_inventory_snapshot,
    build_skill_lifecycle_evidence_index,
    build_skill_lifecycle_compatibility_report,
    build_skill_lock_file,
    build_skill_selection_decisions,
    build_skill_support_bundle_projection,
    build_skill_usage_summary,
    diff_skill_inventories,
    inventory_record_from_manifest,
    invocation_record_from_view,
    project_skill_harness_adapter_events,
    project_skill_harness_artifact_refs,
    project_skill_lifecycle_hook_audit_records,
    project_skill_support_bundle_refs,
    read_skill_lock_file,
    render_skill_lifecycle_markdown,
    replay_skill_lifecycle_from_artifacts,
    seed_chat_demo_skill_lifecycle_report,
    seed_excel_skill_lifecycle_report,
    skill_attachment_from_record,
    stable_skill_id,
    support_bundle_projection,
    supporting_file_refs,
    write_skill_lifecycle_artifacts,
    write_skill_lock_file,
)
from agent_driver.skills.render import render_skill_entry

__all__ = [
    "SKILL_FILENAME",
    "clear_skill_manifest_cache",
    "SkillInvocation",
    "SkillManifest",
    "SkillView",
    "CURATED_RESEARCH_SKILL_NAMES",
    "build_skills_catalog_block",
    "build_skill_lifecycle_evidence_index",
    "build_skill_inventory_snapshot",
    "build_skill_lifecycle_compatibility_report",
    "build_skill_lock_file",
    "build_skill_selection_decisions",
    "build_skill_support_bundle_projection",
    "build_skill_usage_summary",
    "curated_skills_dir",
    "diff_skill_inventories",
    "inventory_record_from_manifest",
    "invocation_record_from_view",
    "project_skill_harness_adapter_events",
    "project_skill_harness_artifact_refs",
    "project_skill_lifecycle_hook_audit_records",
    "project_skill_support_bundle_refs",
    "is_trusted_path",
    "list_skill_manifests",
    "load_skill_manifest",
    "parse_frontmatter",
    "read_skill_lock_file",
    "render_skill_lifecycle_markdown",
    "replay_skill_lifecycle_from_artifacts",
    "render_skill_entry",
    "seed_chat_demo_skill_lifecycle_report",
    "seed_excel_skill_lifecycle_report",
    "skill_attachment_from_record",
    "skill_manifest_payload",
    "stable_skill_id",
    "split_frontmatter",
    "support_bundle_projection",
    "supporting_file_refs",
    "view_skill",
    "write_skill_lifecycle_artifacts",
    "write_skill_lock_file",
]
